### ISSUE TITLE
Minor spelling mistakes

### ISSUE THREAD

**Issue by Harvester62** [Digiography/blender_addon_pbr#1]
Hello. First of all thank you for this add-on recently submitted for evaluation and approval.

I noticed a couple of minor spelling mistakes in file "__init__.py":

Row 272: should read "Occlusion" and not "Occlussion"
Row 273: The same as above and I would suggest to use "RGB Mix" intead of "RGBMIX"

The above applies also to Rows 357, 358, and 415, 

So not really a bug. Thanks.

**Comment by DigiKrafting** [comment]
Thanks Harvester62 , I've just updated with corrected spelling.
