### ISSUE TITLE
Auto update security concern

### ISSUE THREAD

**Issue by Harvester62** [Digiography/blender_addon_pbr#2]
It's me again, and this time this is about a potential security issue concern. The auto update functionality embedded in your add-on, despite being an option the user can activare or not, I think it should be removed to avoid security breach as already being discussed here:

https://lists.blender.org/pipermail/bf-committers/2017-October/048818.html

Thanks and regards.

**Comment by DigiKrafting** [comment]
The auto update feature has been removed as suggested for security reasons.
