### ISSUE TITLE
Misspelled layout property for specular node

### ISSUE THREAD

**Issue by Harvester62** [Digiography/blender_addon_pbr#5]
Hello,

I've found a mistake in the code at line 505 which generates this error message in the Blender console:

D:\Blender_2.79b_stable\2.79\scripts\addons_extern\blender_addon_pbr\__init__.py:505
rna_uiItemR: property not found: ds_pbr_addon_prefs.option_Specular_node

Reason is that the value 'option_Specular_node' should be all lowercase and read as follows: 

        layout.prop(self, 'option_specular_node')

Regards.

**Comment by DigiKrafting** [comment]
Hi Harvester62,

Thanks for reporting the bug, I use the metallic workflow so I didn't come across this. The fix has been uploaded.
