### ISSUE TITLE
Principled Shader does NOT support spec/gloss workflow

### ISSUE THREAD

**Issue by qforce85** [Digiography/blender_addon_pbr#6]
Hi,

sorry to break this to you, but it is totally wrong to use the Principled Shader for a spec/gloss workflow the way this addon does it. The reason why it's wrong is rather complex; I suggest reading the following introductions to PBR:

[Physically Based Rendering Encyclopedia](https://docs.google.com/document/d/1Fb9_KgCo0noxROKN4iT8ntTbx913e-t4Wc2nMRWPzNk/edit)

[PBR Guide](https://www.allegorithmic.com/pbr-guide)

In a nutshell, you can't just plug a specular map from the spec/gloss workflow into the specular input of the Principled Shader, because (1) values of the specular input in the range 0-1 correspond to 0-8% of "actual" specular reflection, (2) the specular input is ignored when metalness is set to 1, and (3) the specular input is a value, whereas specular maps may contain color information in the case of metals. See also the [Blender documentation on the Principled Shader](https://docs.blender.org/manual/en/latest/render/cycles/nodes/types/shaders/principled.html).

Best regards
q:-) <= Quang

**Comment by qforce85** [comment]
I wrote a proposal over at Right-Click Select explaining what the specular socket really does and why it should be renamed to "Specular Level": [https://blender.community/c/rightclickselect/t1cbbc/principled-shader-rename-specular-socket-to-specul](https://blender.community/c/rightclickselect/t1cbbc/principled-shader-rename-specular-socket-to-specul)

**Comment by DigiKrafting** [comment]
Thank you for letting me know, I created this addon after watching some video tutorials on the then, new shader, I'll update the specular nodes when I have some free time.
