### ISSUE TITLE
ds_pbr.material' doesn't contain '_PT_'

### ISSUE THREAD

**Issue by agarzon** [Digiography/blender_addon_pbr#7]
I'm not expert at all, in fact i never coded in python. 

I'm just reporting what I see in the logs as soon this addon is installed.

```
register_class(...):
Warning: 'ds_pbr.material' doesn't contain '_PT_' with prefix & suffix
```

**Comment by DigiKrafting** [comment]
Thanks for reporting the bug agarzon, I've uploaded a fix: https://github.com/Digiography/blender_addon_pbr/releases/tag/2_5_1
